{{alias}}
sss = +forward-override{forward-socks5t 192.168.1.1:1080 .} \
      +change-x-forwarded-for{block}
tor = +forward-override{forward-socks4a 127.0.0.1:9150 .} \
      +change-x-forwarded-for{block} \
      +client-header-filter{hide-tor-exit-notation}
i2p = +forward-override{forward 127.0.0.1:4444} \
      +change-x-forwarded-for{block}

{ sss }

# Top level domains
.org
.au
.sg
.io
.me
.ai
.sk
.dev
.tw
.jp
.global
.gov
.us
.mil
.uk
.ca
.eu
.ru
.gg
.tv
.dj
.fm
.ly
.it
.vc
.gs
.bz
.cc
.im
.to
.is
.asia
.news
.wiki
.media
.app
.biz
.tech
.icu
.xyz
.space
.digital
.report
.press

# X a.k.a. Twitter
.twimg.com
.twitter.com
.t.co
.x.co
.x.com
.ads-twitter.com

# Google
.gstatic.
.googleapis.com
.google.
#.google
.googlevideo.com
.ytimg.com
.youtube.com
.ggpht.com
.googleusercontent.com
.g.co
.googledrive.com
.googletagmanager.com
.googletagservices.com
.google-analytics.com
.app-analytics-services.com
.app-measurement.com
.crashlytics.com
.gvt3.com
.gvt2.com
.gvt1.com
.gvt0.com
.doubleclick.
.googleadservices.com
.googleadsserving.
.googlesyndication.com
.firebaseapp.com
.firebaseio.com
.recaptcha.net
.youtube-nocookie.com
.youtu.be
.goo.gl
.goo.gle
.goog
.gmail.com
.googlemail.com
.android.com
.chrome.com
.googleblog.com
.blogspot.
.blogger.com
.blogblog.com
.googlegroups.com
.googlesource.com
.waze.com
.appspot.com
.googlehosted.com
.googlelabs.com
.withgoogle.com
.thinkwithgoogle.com

# Apple
.icloud.com
.icloud-content.com
.apple-cloudkit.com
.mzstatic.com
.cdn-apple.com
.apple-dns.net
.apple

# Yahoo!
.yimg.
.yahooapis.com
.yahoo.
.yahoodns.net
.ymail.com
.yusercontent.com
.flickr.com
.staticflickr.com
.yahoosandbox.com

# Microsoft
.github.
.githubusercontent.com
.githubassets.com
.githubapp.com
.githubcopilot.com
.live.com
.live.net
.linkedin.

# News
.afr.com
.bbc.com
#.bbc.co.uk
#.bbci.co.uk
.bbcchinese.com
.bbc.in
.voanews.com
.voachinese.com
.dw.de
.dw.com
.rfi.fr
.rfi.my
.nyti.ms
.nytimes.com
.nyt.com
.nytco.com
.nytcn.com
.nytlog.com
.nytstyle.com
.nytmediakit.com
.tmagazine.com
.wsj.com
.wsj.net
.ft.com
.ftchinese.com
.economist.com
.econ.st
.theguardian.com
.reuters.com
.theatlantic.com
.foreignaffairs.com
.ti.me
.time.com
.timeinc.net
.apnews.com
#.ap.org
#.aptv.org
.apimages.com
.forbes.com
.bloomberg.com
.trib.al
.businessweek.com
.businessinsider.com
.cnn.
.turner.com
.washingtonpost.com
.wpdigital.net
.wapo.st
.rfachina.com
.nikkei.com
.scmp.com
.sc.mp
.hk01.com
.zaobao.com
.chinadigitaltimes.net
.v2ex.com

# Tools
.duckduckgo.
.sstatic.net
.openai.com
.oaistatic.com
.oaiusercontent.com
.chatgpt.com
.anthropic.com
#.redd.it
.reddit.com
.redditmedia.com
.redditlist.com
.redditstatic.com
.redditspace.com
#.mozilla.org
.mozilla.net
.mozilla.com
.firefox.com
.mozgcp.net
.wordpress.
.wp.com
.gravatar.com
.dropbox.com
.dropboxusercontent.com
.dropboxstatic.com
.box.com
.pastebin.com
.imgur.com
.substack.com
.z-library.
.cdn-zlib.
.go-to-library.
.singlelogin.
#.zlibrary-redirect.org
.quora.com
.quoracdn.net
.ycombinator.com
.medium.com
.ted.com
.tedcdn.com
.pinterest.com
.feedblitz.com
.vimeo.com
.vimeocdn.com

# DNS
.akadns.net
.cloudflare-dns.com
.opendns.com
.quad9.net
.dyndns.org

# Meta
.facebook.
.fbcdn.net
.fb.com
.instagram.com
.cdninstagram.com
.instagr.am
.whatsapp.
.meta.com
.thefacebook.com
.fbsbx.com

