#!/bin/sh

# ~/.vnc/xstartup

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

if command -v autocutsel >/dev/null 2>&1; then
     autocutsel -s CLIPBOARD -fork
fi
vncconfig -nowin &

tint2 &

x-terminal-emulator &

exec openbox

